if(NOT DEFINED WORKER OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "WORKER and OUTPUT_DIR required")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
# This harness owns the named generated fixture; the adapter itself rejects overwrite.
file(REMOVE "${OUTPUT_DIR}/host_000.rpl")
function(run_worker mode replay output)
    execute_process(COMMAND "${WORKER}" "${mode}" "${replay}" "${OUTPUT_DIR}/${output}"
        RESULT_VARIABLE result OUTPUT_VARIABLE log ERROR_VARIABLE errors TIMEOUT 240)
    file(WRITE "${OUTPUT_DIR}/${output}.log" "${log}\n${errors}")
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "${mode} failed: ${result}\n${log}\n${errors}")
    endif()
endfunction()
run_worker(record "${OUTPUT_DIR}/host.rpl" baseline)
run_worker(live unused reordered)
run_worker(replay "${OUTPUT_DIR}/host_000.rpl" playback)
run_worker(seek "${OUTPUT_DIR}/host_000.rpl" restarted)
function(compare left right)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E compare_files "${OUTPUT_DIR}/${left}" "${OUTPUT_DIR}/${right}" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Host process output differs: ${left} vs ${right}")
    endif()
endfunction()
compare(baseline.trace reordered.trace)
compare(baseline.trace playback.trace)
compare(baseline.tail.trace restarted.trace)
compare(baseline.state reordered.state)
compare(baseline.state playback.state)
compare(baseline.state restarted.state)
message(STATUS "PASS: real Host 10000 ticks across presentation rates, record/live/replay/seek and pause/restore/single-step")
