if(NOT DEFINED WORKER OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "WORKER and OUTPUT_DIR required")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
function(run_worker mode replay output)
    execute_process(COMMAND "${WORKER}" "${mode}" "${replay}" "${OUTPUT_DIR}/${output}"
        RESULT_VARIABLE result OUTPUT_VARIABLE log ERROR_VARIABLE errors TIMEOUT 120)
    file(WRITE "${OUTPUT_DIR}/${output}.log" "${log}\n${errors}")
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "${mode} failed: ${result}\n${log}\n${errors}")
    endif()
endfunction()
run_worker(record "${OUTPUT_DIR}/session.rpl" baseline)
run_worker(live unused reordered)
run_worker(replay "${OUTPUT_DIR}/session_000.rpl" playback)
run_worker(seek "${OUTPUT_DIR}/session_000.rpl" restarted)
function(compare left right)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E compare_files "${OUTPUT_DIR}/${left}" "${OUTPUT_DIR}/${right}" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Deterministic process output differs: ${left} vs ${right}")
    endif()
endfunction()
compare(baseline.trace reordered.trace)
compare(baseline.trace playback.trace)
compare(baseline.tail.trace restarted.trace)
compare(baseline.state reordered.state)
compare(baseline.state playback.state)
compare(baseline.state restarted.state)
message(STATUS "PASS: 10000 tick hashes across independent live/reordered/replay processes; 5000 checkpoint suffix; canonical final fields identical")
