if(NOT DEFINED WORKER OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "WORKER and OUTPUT_DIR required")
endif()
get_filename_component(_controller_output "${OUTPUT_DIR}" ABSOLUTE)
file(MAKE_DIRECTORY "${_controller_output}")
# This harness owns only this one generated recording in its dedicated test directory.
file(REMOVE "${_controller_output}/character_000.rpl")
function(run_worker mode replay output)
    execute_process(COMMAND "${WORKER}" "${mode}" "${replay}" "${_controller_output}/${output}"
        RESULT_VARIABLE result OUTPUT_VARIABLE log ERROR_VARIABLE errors TIMEOUT 180)
    file(WRITE "${_controller_output}/${output}.log" "${log}\n${errors}")
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "${mode} failed: ${result}\n${log}\n${errors}")
    endif()
endfunction()
run_worker(record "${_controller_output}/character.rpl" baseline)
run_worker(live unused reordered)
run_worker(replay "${_controller_output}/character_000.rpl" playback)
run_worker(seek "${_controller_output}/character_000.rpl" restarted)
function(compare left right)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E compare_files "${_controller_output}/${left}" "${_controller_output}/${right}" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Controller Host outputs differ: ${left} vs ${right}")
    endif()
endfunction()
compare(baseline.trace reordered.trace)
compare(baseline.trace playback.trace)
compare(baseline.tail.trace restarted.trace)
compare(baseline.state reordered.state)
compare(baseline.state playback.state)
compare(baseline.state restarted.state)
message(STATUS "PASS: controller real Host 2048 ticks, presentation rates, record/live/replay/seek, pause/restore/single-step and full state/trace equality")
