# design reference: AYEntity/design.md Stage19; independent application runners.
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(work "${OUTPUT}/process cases ${nonce}")
file(MAKE_DIRECTORY "${work}")
function(run expected)
    execute_process(COMMAND "${TOOL}" ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
    if(NOT "${result}" STREQUAL "${expected}")
        message(FATAL_ERROR "CLI expected${expected}, got${result}: ${output}\n${error}")
    endif()
    set(last_output "${output}" PARENT_SCOPE)
endfunction()
run(0 verify "${FIXTURE}" "${RUNNER}" "${work}/verified & spaces")
file(READ "${work}/verified & spaces/report.json" report)
if(NOT report MATCHES "\"result\":\"verified\"")
    message(FATAL_ERROR "Missing executed verification result: ${report}")
endif()
run(1 verify "${FIXTURE}" "${FAULT}" "${work}/failure & repro")
file(READ "${work}/failure & repro/report.json" report)
if(NOT report MATCHES "\"result\":\"state-mismatch\"" OR NOT report MATCHES "\"tick\":96" OR NOT report MATCHES "\"epoch\":2")
    message(FATAL_ERROR "Expected injected logic divergence: ${report}")
endif()
run(1 reproduce "${work}/failure & repro" "${FAULT}" "${work}/reproduced")
file(READ "${work}/reproduced/report.json" reproduced)
if(NOT reproduced MATCHES "\"result\":\"state-mismatch\"" OR NOT reproduced MATCHES "\"ticksExecuted\":1" OR NOT reproduced MATCHES "\"tick\":96")
    message(FATAL_ERROR "Independent minimal repro failed: ${reproduced}")
endif()
foreach(key IN ITEMS entity component field lane section expected actual tick)
    string(JSON original_value GET "${report}" difference ${key})
    string(JSON reproduced_value GET "${reproduced}" difference ${key})
    if(NOT "${original_value}" STREQUAL "${reproduced_value}")
        message(FATAL_ERROR "Repro differs in ${key}: ${original_value} vs ${reproduced_value}")
    endif()
endforeach()
run(0 reproduce "${work}/failure & repro" "${RUNNER}" "${work}/repro-correct-logic")
run(0 compare "${FIXTURE}" "${FIXTURE}" "${work}/equal")
run(1 verify "${FIXTURE}" "${SLOW}" "${work}/timeout" 20)
if(NOT last_output MATCHES "\"timedOut\":true" OR EXISTS "${work}/timeout/report.json")
    message(FATAL_ERROR "Deadline must not publish verified report: ${last_output}")
endif()
run(1 verify "${FIXTURE}" "${work}/missing runner" "${work}/not-launched")
run(1 verify "${FIXTURE}" "${NOREPORT}" "${work}/missing-report")
if(NOT last_output MATCHES "\"reportPresent\":false")
    message(FATAL_ERROR "Exit0 without protocol report is not successful verification")
endif()
run(2 verify "${FIXTURE}" "${RUNNER}" "${work}/invalid-timeout" 0)
run(2 verify "${FIXTURE}" "${RUNNER}" "${work}/invalid-timeout-text" invalid)
message(STATUS "PASS independent replay verify/reproduce/compare, shell-free spaced paths, missing runner and bounded deadline; artifacts=${work}")
