# design reference: AYEntity/design.md Stage20; seeded simulation and scene-query gates.
if(NOT DEFINED _simulation_campaign_library)
    set(_simulation_campaign_library AYEntityDeterminismKernel)
endif()
add_executable(AYEntity_SimulationCampaign
    "${AYENTITY_ROOT}/unittest/portable/simulationcampaign.cpp"
    "${AYENTITY_ROOT}/unittest/portable/contextfault.cpp")
target_link_libraries(AYEntity_SimulationCampaign PRIVATE ${_simulation_campaign_library})
target_compile_features(AYEntity_SimulationCampaign PRIVATE cxx_std_23)
add_executable(AYEntity_CollisionQueryChecks "${AYENTITY_ROOT}/unittest/portable/collisionquery.cpp")
target_link_libraries(AYEntity_CollisionQueryChecks PRIVATE ${_simulation_campaign_library})
target_compile_features(AYEntity_CollisionQueryChecks PRIVATE cxx_std_23)
if(MSVC)
    target_compile_options(AYEntity_SimulationCampaign PRIVATE /utf-8)
    target_compile_options(AYEntity_CollisionQueryChecks PRIVATE /utf-8)
endif()
set(_simulation_artifacts "${CMAKE_CURRENT_BINARY_DIR}/simulation-campaign-artifacts")
add_test(NAME AYEntity_ContextFaultChecks COMMAND AYEntity_SimulationCampaign --context-only --output "${_simulation_artifacts}/context")
set_tests_properties(AYEntity_ContextFaultChecks PROPERTIES TIMEOUT 120)
add_test(NAME AYEntity_SimulationCampaign COMMAND AYEntity_SimulationCampaign --seed 20261010 --cases 8 --ticks 256 --output "${_simulation_artifacts}/simulation")
set_tests_properties(AYEntity_SimulationCampaign PROPERTIES TIMEOUT 180)
add_test(NAME AYEntity_SimulationCampaignShortCase COMMAND AYEntity_SimulationCampaign --seed 189145 --cases 1 --ticks 16 --output "${_simulation_artifacts}/short-case")
set_tests_properties(AYEntity_SimulationCampaignShortCase PROPERTIES TIMEOUT 120)
add_test(NAME AYEntity_CollisionQueryChecks COMMAND AYEntity_CollisionQueryChecks --seed 20261010 --cases 128 --output "${_simulation_artifacts}/queries")
set_tests_properties(AYEntity_CollisionQueryChecks PROPERTIES TIMEOUT 120)
